from __future__ import annotations
# Autogenerated bridge so `utilities.performance_tracker` resolves consistently in Cloud/Local.
# It prefers AstroLotto's implementation, then BreakoutBuddy's, and finally file-path loading.

from pathlib import Path
import importlib, importlib.util, sys

def _load_impl():
    # Try normal package imports
    try:
        return importlib.import_module("AstroLotto.programs.utilities.performance_tracker")
    except Exception:
        pass
    try:
        return importlib.import_module("BreakoutBuddy.program.utilities.performance_tracker")
    except Exception:
        pass

    # Fallback: load by file path relative to this file
    root = Path(__file__).resolve().parent.parent
    candidates = [
        root / "AstroLotto" / "programs" / "utilities" / "performance_tracker.py",
        root / "BreakoutBuddy" / "program" / "utilities" / "performance_tracker.py",
    ]
    for c in candidates:
        if c.exists():
            spec = importlib.util.spec_from_file_location(f"__bridge_util_performance_tracker__", c)
            if spec and spec.loader:
                mod = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(mod)  # type: ignore[attr-defined]
                return mod
    raise ModuleNotFoundError("utilities.performance_tracker bridge could not locate an implementation")

_impl = _load_impl()

# Re-export public attributes
globals().update({k: getattr(_impl, k) for k in dir(_impl) if not k.startswith("_")})
